services:
  atcoder:
    image: atcoder:0.1.0
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        PYTHON_VERSION: 3.11
        REQUIREMENTS: .devcontainer/requirements.txt
    tty: true
    volumes:
      - .:/app
